version: '3'
services:
  node1:
    image: blockchain
    container_name: first
    build: .
    command: "node1 8000"
  node2:
    image: blockchain
    container_name: second
    build: .
    command: "node2 8001"
  node3:
    image: blockchain
    container_name: third
    build: .
    command: "node3 8002"
